In [1]:
import numpy as np

c = np.array([1,2,3])
print(c.shape)

print(c[0])

(3,)
1


In [3]:
r = np.array([[1,2,3]  ]) # row 를 뜻함
print(r.shape) #(1*3)

print(r[0,1])

(1, 3)
2


In [4]:
a = np.zeros((2,2)) # 2x2행렬을 모두 0으로 채운다. 
print(a)

b = np.ones((2,2)) # 2x2행렬을 모두 1로 채운다. 
print(b)

c = np.full((2,2),7) # 2x2행렬을 모두 7로 채운다.
print(c)

d = np.random.random((2,2)) #2x2 행렬을 모두 랜덤한 값으로 채운다. 
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[0.52492463 0.75187959]
 [0.66848351 0.88845074]]


In [5]:
A = np.array([[1,2], [3,4],[5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
B = np.array([[11,12,13,14],[15,16,17,18]])
B

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [7]:
 A.T #transpose a matix

array([[1, 3, 5],
       [2, 4, 6]])

In [9]:
np.dot(A,B) #곱을 할때는 dot사용

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

In [10]:
np.dot(B,A) #사이즈로 인한 에러 발생

ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

In [11]:
A = np.array([[60, 5.5, 1], [65, 5.0, 0],[55, 6.0, 1]])
b = np.array([66, 70, 78])

In [12]:
eye3 = np.eye(3)
eye3 # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
from numpy.linalg import inv #inverse matrix구하는 함수
A_inv = inv(A)
A_inv


array([[ 0.08695652,  0.00869565, -0.08695652],
       [-1.13043478,  0.08695652,  1.13043478],
       [ 2.        , -1.        , -1.        ]])

In [14]:
A * A_inv #In이 나오지 않음 --> matrix곱을 나타내지 않음

array([[ 5.21739130e+00,  4.78260870e-02, -8.69565217e-02],
       [-7.34782609e+01,  4.34782609e-01,  0.00000000e+00],
       [ 1.10000000e+02, -6.00000000e+00, -1.00000000e+00]])

In [15]:
A.dot(A_inv) #실제 matrix의 곱을 하는 dot을 사용해야함

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
x = A_inv.dot(b)
x
#행렬 방정식 풀기

array([ -0.43478261,  19.65217391, -16.        ])

In [17]:
from numpy.linalg import solve
x = solve(A,b) #A -> 데이터, b-> 타깃
x #solve는 행렬식을 바로 풀어주는 함수

array([ -0.43478261,  19.65217391, -16.        ])